package(default_visibility = ["//visibility:public"])

cc_test(
    name = "gtest_smoke_test",
    srcs = ["gtest_smoke_test.cc"],
    deps = [
        "@com_google_googletest//:gtest_main",
    ],
)
