package(default_visibility = ["//visibility:public"])

cc_binary(
    name = "spdlog_test",
    srcs = ["spdlog_test.cc"],
    copts = [
        "-std=c++17",
    ],
    deps = [
        "@spdlog//:spdlog",
    ],
)
