package(default_visibility = ["//visibility:public"])

cc_binary(
    name = "lz4_test",
    srcs = ["lz4_test.cc"],
    copts = [
        "-std=c++11",
    ],
    deps = [
        "@lz4//:lz4",
    ],
)
